version: '3'

services:
  php:
    build:
      context: .
    ports:
      - "8000:8000"
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - database
      - test_database
    command: 
      - "symfony"
      - "server:start"
      - "--no-tls"
      - "--port=8000"
      - "--allow-http"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_SECRET=SomeRandom
      - DATABASE_HOST=database
      - DATABASE_NAME=prod_db_name
      - DATABASE_USER=prod_db_user
      - DATABASE_PASSWORD=prod_db_password
      - TEST_DATABASE_HOST=test_database
      - TEST_DATABASE_NAME=test_db_name
      - TEST_DATABASE_USER=test_db_user
      - TEST_DATABASE_PASSWORD=test_db_password

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: prod_db_name
      POSTGRES_PASSWORD: prod_db_password
      POSTGRES_USER: prod_db_user
    volumes:
      - prod_database_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["docker-entrypoint.sh", "postgres", "-c", "log_statement=all"]

  test_database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: test_db_name
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_USER: test_db_user
    volumes:
      - test_database_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["docker-entrypoint.sh", "postgres", "-c", "log_statement=all"]

volumes:
  prod_database_data:
  test_database_data:
