#!/bin/bash

# Run PHPStan
echo "Running PHPStan..."
vendor/bin/phpstan analyze

# Run PHP CS Fixer
echo "Running PHP CS Fixer..."
vendor/bin/php-cs-fixer fix --dry-run --verbose --diff

# If PHPStan and PHP CS Fixer return 0, allow the commit
if [ $? -eq 0 ]; then
    exit 0
else
    echo "PHPStan or PHP CS Fixer found issues. Commit aborted."
    exit 1
fi
