#!/bin/bash

echo "Running PHPStan..."
vendor/bin/phpstan analyze

echo "Running PHP CS Fixer..."
vendor/bin/php-cs-fixer fix --dry-run --verbose --diff

if [ $? -eq 0 ]; then
    exit 0
else
    echo "PHPStan or PHP CS Fixer found issues. Commit aborted."
    exit 1
fi
