#!/bin/bash

vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no

CS_FIXER_RESULT=$?
if [ $CS_FIXER_RESULT -ne 0 ]; then
    echo "php-cs-fixer detected issues. Please fix them before committing."
    exit 1
fi

vendor/bin/phpstan analyse

PHPSTAN_RESULT=$?
if [ $PHPSTAN_RESULT -ne 0 ]; then
    echo "phpstan detected issues. Please fix them before committing."
    exit 1
fi

exit 0
