add_product_to_cart:
    path: /carts/{userId}/add/{productId}
    controller: App\Controller\ShoppingCartController::addProductToCart
    methods: POST

remove_product_from_cart:
    path: /carts/{userId}/remove/{productId}
    controller: App\Controller\ShoppingCartController::removeProductFromCart
    methods: DELETE

update_product_quantity:
    path: /carts/{userId}/update/{productId}
    controller: App\Controller\ShoppingCartController::updateProductQuantityinCart
    methods: PUT

get_cart:
    path: /carts/{userId}
    controller: App\Controller\ShoppingCartController::getCart
    methods: GET

get_carts:
    path: /carts
    controller: App\Controller\ShoppingCartController::getCarts
    methods: GET

create_product:
    path: /products/create
    controller: App\Controller\ProductController::createProduct
    methods: POST

update_product:
    path: /products/update/{productId}
    controller: App\Controller\ProductController::updateProduct
    methods: PUT

delete_product:
    path: /products/delete/{productId}
    controller: App\Controller\ProductController::deleteProduct
    methods: DELETE

get_product:
    path: /products/{productId}
    controller: App\Controller\ProductController::getProduct
    methods: GET

get_products:
    path: /products
    controller: App\Controller\ProductController::getProducts
    methods: GET

get_user:
    path: /users/{userId}
    controller: App\Controller\UserController::getUserById
    methods: GET

get_all_users:
    path: /users
    controller: App\Controller\UserController::getAllUsers
    methods: GET

create_user:
    path: /users/create
    controller: App\Controller\UserController::createUser
    methods: POST

update_user:
    path: /users/update/{userId}
    controller: App\Controller\UserController::updateUser
    methods: PUT

delete_user:
    path: /users/delete/{userId}
    controller: App\Controller\UserController::deleteUser
    methods: DELETE
