update_cart:
    path: /cart/update/{userId}
    controller: App\Controller\CartController::updateCart
    methods: PUT

get_cart:
    path: /cart/{userId}
    controller: App\Controller\CartController::getCart
    methods: GET

get_carts:
    path: /carts
    controller: App\Controller\CartController::getCarts
    methods: GET

create_product:
    path: /product/create
    controller: App\Controller\ProductController::createProduct
    methods: POST

update_product:
    path: /product/update/{productid}
    controller: App\Controller\ProductController::updateProduct
    methods: PUT

delete_product:
    path: /product/delete/{productid}
    controller: App\Controller\ProductController::deleteProduct
    methods: DELETE

get_product:
    path: /product/{productId}
    controller: App\Controller\ProductController::getProduct
    methods: GET

get_products:
    path: /products
    controller: App\Controller\ProductController::getProducts
    methods: GET

get_user:
    path: /user/{userId}
    controller: App\Controller\UserController::getUser
    methods: GET

get_all_users:
    path: /users
    controller: App\Controller\UserController::getAllUsers
    methods: GET

create_user:
    path: /user/create
    controller: App\Controller\UserController::createUser
    methods: POST

update_user:
    path: /user/update/{userId}
    controller: App\Controller\UserController::updateUser
    methods: PUT

delete_user:
    path: /user/delete/{userId}
    controller: App\Controller\UserController::deleteUser
    methods: DELETE
