services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\ProductService:
        arguments: 
            $productRepository: '@App\Repository\ProductRepository'
            $validator: '@validator'

    App\Controller\ProductController:
        arguments:
            $productService: '@App\Service\ProductService'